### ISSUE TITLE
The image `landoop/lenses:v2.0.0` cannot be found in docker hub registry

### ISSUE THREAD

**Issue by smallcampus** [Landoop/kafka-helm-charts#14]
https://github.com/Landoop/kafka-helm-charts/blob/master/charts/lenses/values.yaml

The image `landoop/lenses:v2.0.0` cannot be found in docker hub registry.

```
image:
  repository: landoop/lenses
  tag: v2.0.0
  pullPolicy: IfNotPresent
```
